name: social_media_app
description: A social medial app using flutter and firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.5"

dependencies:
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.4.4
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  firebase_storage: ^10.3.5
  flutter:
    sdk: flutter 
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.9
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  image_picker: ^0.8.5+3
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner:
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  lint: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/generated/

flutter_intl:
  enabled: true

flutter_icons:
  image_path: assets/icon/icon.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: '#ffffff'
  image: assets/icon/icon.png
  android: true
  android_12:
    image: assets/icon/icon.png
  ios: true