name: social_media_app
description: A social medial app using flutter and firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter 
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.11
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/