name: social_media_app
description: A social medial app using flutter and firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter 

dev_dependencies:
  build_runner: ^2.1.11
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/