// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtTfOo4R03PiXKM0J3QCmq-pNN592Ir6U',
    appId: '1:649028464951:web:ebc92744a9e65ebe422ab2',
    messagingSenderId: '649028464951',
    projectId: 'social-media-app-996',
    authDomain: 'social-media-app-996.firebaseapp.com',
    storageBucket: 'social-media-app-996.appspot.com',
    measurementId: 'G-VN77WTP42S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1jVhblJj--JyhgQfytvdyyWyWRuGtsk',
    appId: '1:649028464951:android:ed6c7eaec36eae42422ab2',
    messagingSenderId: '649028464951',
    projectId: 'social-media-app-996',
    storageBucket: 'social-media-app-996.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcbVuhzIoTvoUMMSI24eKN3T_EpVeLwXQ',
    appId: '1:649028464951:ios:c5f4b264dae9c0c8422ab2',
    messagingSenderId: '649028464951',
    projectId: 'social-media-app-996',
    storageBucket: 'social-media-app-996.appspot.com',
    iosClientId: '649028464951-ookeu178tl6mvh197m79mni6vktf6c5t.apps.googleusercontent.com',
    iosBundleId: 'com.omarassem.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcbVuhzIoTvoUMMSI24eKN3T_EpVeLwXQ',
    appId: '1:649028464951:ios:c5f4b264dae9c0c8422ab2',
    messagingSenderId: '649028464951',
    projectId: 'social-media-app-996',
    storageBucket: 'social-media-app-996.appspot.com',
    iosClientId: '649028464951-ookeu178tl6mvh197m79mni6vktf6c5t.apps.googleusercontent.com',
    iosBundleId: 'com.omarassem.socialMediaApp',
  );
}
